import "./globals.css";
import { Analytics } from "@vercel/analytics/react";

export const metadata = {
  title: "Globes | Giant-Balls",
  description: "Definately Not Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="overflow-x-hidden">
        {children}
        <Analytics />
      </body>
    </html>
  );
}
